name: GitHub Classroom Workflow

on: [push]


permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/setup-node@v3
        with:
         node-version: 16
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
